# Matrices Ejercicio Clase 1
## Nicolás Salusso - 10710

En primer lugar se van construir las siguientes matrices utilizando la libreria numpy:

A = \begin{bmatrix}
        1 & 2 & 3 \\
        4 & 5 & 6
    \end{bmatrix}


In [21]:
from numpy import array

a = array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])



B = \begin{bmatrix}
        -1 & 0 \\
        1 & 1 \\
        0 & 1
    \end{bmatrix}

In [22]:
b = array([[-1, 0], [1, 1], [0, 1]])
b

array([[-1,  0],
       [ 1,  1],
       [ 0,  1]])

## Operaciones:
### $A-B^T$

#### Documentación:
* transpose()
	https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.transpose.html

In [23]:
op_1 = a - b.transpose()
op_1

array([[2, 1, 3],
       [4, 4, 5]])

### $(A.B)^{-1}$

#### Documentación:
* matmul() https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.matmul.html
* linalg.inv() https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html


In [26]:
from numpy import linalg, matmul
op_2 = matmul(a, b)
op_2 = linalg.inv(op_2)
op_2

array([[ 1.83333333, -0.83333333],
       [-0.16666667,  0.16666667]])

Fin
